export const GET_ARTWORKS = "GET_ARTWORKS";
export const GET_ARTWORKS_OK = "GET_ARTWORKS_OK";
export const GET_ARTWORKS_FAIL = "GET_ARTWORKS_FAIL";

export const GET_SINGLE_ARTWORK = "GET_SINGLE_ARTWORK";
export const GET_SINGLE_ARTWORK_OK = "GET_SINGLE_ARTWORK_OK";
export const GET_SINGLE_ARTWORK_FAIL = "GET_SINGLE_ARTWORK_FAIL";

export const GET_SEARCH = "GET_SEARCH";
export const GET_SEARCH_OK = "GET_SEARCH_OK";
export const GET_SEARCH_FAIL = "GET_SEARCH_FAIL";